# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'View.ui'
#
# Created by: PyQt5 UI code generator 5.15.9
#
# WARNING: Any manual changes made to this file will be lost when pyuic5 is
# run again.  Do not edit this file unless you know what you are doing.


from PyQt5 import QtCore, QtGui, QtWidgets


class Ui_MainWindow(object):
    def setupUi(self, MainWindow):
        MainWindow.setObjectName("MainWindow")
        MainWindow.resize(420, 720)
        MainWindow.setMinimumSize(QtCore.QSize(420, 720))
        MainWindow.setMaximumSize(QtCore.QSize(420, 720))
        self.centralwidget = QtWidgets.QWidget(MainWindow)
        self.centralwidget.setObjectName("centralwidget")
        self.pushButton_add = QtWidgets.QPushButton(self.centralwidget)
        self.pushButton_add.setGeometry(QtCore.QRect(290, 670, 120, 40))
        font = QtGui.QFont()
        font.setPointSize(12)
        self.pushButton_add.setFont(font)
        self.pushButton_add.setObjectName("pushButton_add")
        self.lineEdit_group_name = QtWidgets.QLineEdit(self.centralwidget)
        self.lineEdit_group_name.setGeometry(QtCore.QRect(10, 670, 270, 40))
        font = QtGui.QFont()
        font.setPointSize(12)
        self.lineEdit_group_name.setFont(font)
        self.lineEdit_group_name.setObjectName("lineEdit_group_name")
        self.listView_group = QtWidgets.QListView(self.centralwidget)
        self.listView_group.setGeometry(QtCore.QRect(10, 60, 400, 600))
        font = QtGui.QFont()
        font.setPointSize(12)
        self.listView_group.setFont(font)
        self.listView_group.setEditTriggers(QtWidgets.QAbstractItemView.DoubleClicked)
        self.listView_group.setObjectName("listView_group")
        self.pushButton_back = QtWidgets.QPushButton(self.centralwidget)
        self.pushButton_back.setGeometry(QtCore.QRect(10, 10, 120, 40))
        font = QtGui.QFont()
        font.setPointSize(12)
        self.pushButton_back.setFont(font)
        self.pushButton_back.setObjectName("pushButton_back")
        self.label = QtWidgets.QLabel(self.centralwidget)
        self.label.setGeometry(QtCore.QRect(140, 10, 260, 40))
        font = QtGui.QFont()
        font.setPointSize(14)
        font.setBold(True)
        self.label.setFont(font)
        self.label.setAlignment(QtCore.Qt.AlignCenter)
        self.label.setObjectName("label")
        MainWindow.setCentralWidget(self.centralwidget)

        self.retranslateUi(MainWindow)
        QtCore.QMetaObject.connectSlotsByName(MainWindow)

    def retranslateUi(self, MainWindow):
        _translate = QtCore.QCoreApplication.translate
        MainWindow.setWindowTitle(_translate("MainWindow", "MainWindow"))
        self.pushButton_add.setText(_translate("MainWindow", " Add"))
        self.pushButton_back.setText(_translate("MainWindow", " Back"))
        self.label.setText(_translate("MainWindow", "Group Management"))


if __name__ == "__main__":
    import sys
    app = QtWidgets.QApplication(sys.argv)
    MainWindow = QtWidgets.QMainWindow()
    ui = Ui_MainWindow()
    ui.setupUi(MainWindow)
    MainWindow.show()
    sys.exit(app.exec_())
