# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'View.ui'
#
# Created by: PyQt5 UI code generator 5.15.11
#
# WARNING: Any manual changes made to this file will be lost when pyuic5 is
# run again.  Do not edit this file unless you know what you are doing.


from PyQt5 import QtCore, QtGui, QtWidgets


class Ui_MainWindow(object):
    def setupUi(self, MainWindow):
        MainWindow.setObjectName("MainWindow")
        MainWindow.resize(900, 805)
        self.centralwidget = QtWidgets.QWidget(MainWindow)
        self.centralwidget.setObjectName("centralwidget")
        self.label_2 = QtWidgets.QLabel(self.centralwidget)
        self.label_2.setGeometry(QtCore.QRect(30, 20, 151, 40))
        font = QtGui.QFont()
        font.setPointSize(12)
        self.label_2.setFont(font)
        self.label_2.setAlignment(QtCore.Qt.AlignRight|QtCore.Qt.AlignTrailing|QtCore.Qt.AlignVCenter)
        self.label_2.setObjectName("label_2")
        self.pushButton_add = QtWidgets.QPushButton(self.centralwidget)
        self.pushButton_add.setGeometry(QtCore.QRect(480, 700, 60, 40))
        font = QtGui.QFont()
        font.setPointSize(12)
        self.pushButton_add.setFont(font)
        self.pushButton_add.setObjectName("pushButton_add")
        self.lineEdit_name = QtWidgets.QLineEdit(self.centralwidget)
        self.lineEdit_name.setGeometry(QtCore.QRect(30, 700, 440, 40))
        font = QtGui.QFont()
        font.setPointSize(12)
        self.lineEdit_name.setFont(font)
        self.lineEdit_name.setObjectName("lineEdit_name")
        self.listView_name = QtWidgets.QListView(self.centralwidget)
        self.listView_name.setGeometry(QtCore.QRect(30, 70, 500, 601))
        font = QtGui.QFont()
        font.setPointSize(12)
        self.listView_name.setFont(font)
        self.listView_name.setEditTriggers(QtWidgets.QAbstractItemView.DoubleClicked)
        self.listView_name.setObjectName("listView_name")
        self.label_image_1 = QtWidgets.QLabel(self.centralwidget)
        self.label_image_1.setGeometry(QtCore.QRect(550, 70, 320, 240))
        font = QtGui.QFont()
        font.setPointSize(12)
        self.label_image_1.setFont(font)
        self.label_image_1.setFrameShape(QtWidgets.QFrame.Box)
        self.label_image_1.setAlignment(QtCore.Qt.AlignCenter)
        self.label_image_1.setObjectName("label_image_1")
        self.label_image_2 = QtWidgets.QLabel(self.centralwidget)
        self.label_image_2.setGeometry(QtCore.QRect(550, 370, 320, 240))
        font = QtGui.QFont()
        font.setPointSize(12)
        self.label_image_2.setFont(font)
        self.label_image_2.setFrameShape(QtWidgets.QFrame.Box)
        self.label_image_2.setAlignment(QtCore.Qt.AlignCenter)
        self.label_image_2.setObjectName("label_image_2")
        self.pushButton_update_image_1 = QtWidgets.QPushButton(self.centralwidget)
        self.pushButton_update_image_1.setGeometry(QtCore.QRect(600, 320, 221, 40))
        font = QtGui.QFont()
        font.setPointSize(12)
        self.pushButton_update_image_1.setFont(font)
        self.pushButton_update_image_1.setObjectName("pushButton_update_image_1")
        self.pushButton_update_image_2 = QtWidgets.QPushButton(self.centralwidget)
        self.pushButton_update_image_2.setGeometry(QtCore.QRect(600, 620, 221, 40))
        font = QtGui.QFont()
        font.setPointSize(12)
        self.pushButton_update_image_2.setFont(font)
        self.pushButton_update_image_2.setObjectName("pushButton_update_image_2")
        self.comboBox_group = QtWidgets.QComboBox(self.centralwidget)
        self.comboBox_group.setGeometry(QtCore.QRect(190, 20, 300, 40))
        font = QtGui.QFont()
        font.setPointSize(12)
        self.comboBox_group.setFont(font)
        self.comboBox_group.setObjectName("comboBox_group")
        MainWindow.setCentralWidget(self.centralwidget)

        self.retranslateUi(MainWindow)
        QtCore.QMetaObject.connectSlotsByName(MainWindow)

    def retranslateUi(self, MainWindow):
        _translate = QtCore.QCoreApplication.translate
        MainWindow.setWindowTitle(_translate("MainWindow", "MainWindow"))
        self.label_2.setText(_translate("MainWindow", "Group Name:"))
        self.pushButton_add.setText(_translate("MainWindow", "Add"))
        self.label_image_1.setText(_translate("MainWindow", "No Image #1"))
        self.label_image_2.setText(_translate("MainWindow", "No Image #2"))
        self.pushButton_update_image_1.setText(_translate("MainWindow", "Update Image #1"))
        self.pushButton_update_image_2.setText(_translate("MainWindow", "Update Image #2"))


if __name__ == "__main__":
    import sys
    app = QtWidgets.QApplication(sys.argv)
    MainWindow = QtWidgets.QMainWindow()
    ui = Ui_MainWindow()
    ui.setupUi(MainWindow)
    MainWindow.show()
    sys.exit(app.exec_())
