# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'View.ui'
#
# Created by: PyQt5 UI code generator 5.15.9
#
# WARNING: Any manual changes made to this file will be lost when pyuic5 is
# run again.  Do not edit this file unless you know what you are doing.


from PyQt5 import QtCore, QtGui, QtWidgets


class Ui_MainWindow(object):
    def setupUi(self, MainWindow):
        MainWindow.setObjectName("MainWindow")
        MainWindow.resize(680, 260)
        MainWindow.setMinimumSize(QtCore.QSize(680, 260))
        MainWindow.setMaximumSize(QtCore.QSize(680, 260))
        self.centralwidget = QtWidgets.QWidget(MainWindow)
        self.centralwidget.setObjectName("centralwidget")
        self.label = QtWidgets.QLabel(self.centralwidget)
        self.label.setGeometry(QtCore.QRect(140, 10, 460, 40))
        font = QtGui.QFont()
        font.setPointSize(14)
        font.setBold(True)
        self.label.setFont(font)
        self.label.setAlignment(QtCore.Qt.AlignCenter)
        self.label.setObjectName("label")
        self.pushButton_back = QtWidgets.QPushButton(self.centralwidget)
        self.pushButton_back.setGeometry(QtCore.QRect(10, 10, 120, 40))
        font = QtGui.QFont()
        font.setPointSize(12)
        self.pushButton_back.setFont(font)
        self.pushButton_back.setObjectName("pushButton_back")
        self.groupBox = QtWidgets.QGroupBox(self.centralwidget)
        self.groupBox.setGeometry(QtCore.QRect(10, 60, 661, 91))
        font = QtGui.QFont()
        font.setPointSize(12)
        self.groupBox.setFont(font)
        self.groupBox.setObjectName("groupBox")
        self.label_number_of_group = QtWidgets.QLabel(self.groupBox)
        self.label_number_of_group.setGeometry(QtCore.QRect(10, 30, 350, 40))
        font = QtGui.QFont()
        font.setPointSize(12)
        self.label_number_of_group.setFont(font)
        self.label_number_of_group.setAlignment(QtCore.Qt.AlignRight|QtCore.Qt.AlignTrailing|QtCore.Qt.AlignVCenter)
        self.label_number_of_group.setObjectName("label_number_of_group")
        self.pushButton_manage_group = QtWidgets.QPushButton(self.groupBox)
        self.pushButton_manage_group.setGeometry(QtCore.QRect(400, 30, 250, 40))
        font = QtGui.QFont()
        font.setPointSize(12)
        self.pushButton_manage_group.setFont(font)
        self.pushButton_manage_group.setObjectName("pushButton_manage_group")
        self.groupBox_2 = QtWidgets.QGroupBox(self.centralwidget)
        self.groupBox_2.setGeometry(QtCore.QRect(10, 160, 661, 91))
        font = QtGui.QFont()
        font.setPointSize(12)
        self.groupBox_2.setFont(font)
        self.groupBox_2.setObjectName("groupBox_2")
        self.pushButton_manage_person = QtWidgets.QPushButton(self.groupBox_2)
        self.pushButton_manage_person.setGeometry(QtCore.QRect(400, 30, 250, 40))
        font = QtGui.QFont()
        font.setPointSize(12)
        self.pushButton_manage_person.setFont(font)
        self.pushButton_manage_person.setObjectName("pushButton_manage_person")
        self.comboBox_group_names = QtWidgets.QComboBox(self.groupBox_2)
        self.comboBox_group_names.setGeometry(QtCore.QRect(90, 30, 300, 40))
        font = QtGui.QFont()
        font.setPointSize(12)
        self.comboBox_group_names.setFont(font)
        self.comboBox_group_names.setObjectName("comboBox_group_names")
        self.label_2 = QtWidgets.QLabel(self.groupBox_2)
        self.label_2.setGeometry(QtCore.QRect(0, 30, 81, 40))
        font = QtGui.QFont()
        font.setPointSize(12)
        self.label_2.setFont(font)
        self.label_2.setAlignment(QtCore.Qt.AlignRight|QtCore.Qt.AlignTrailing|QtCore.Qt.AlignVCenter)
        self.label_2.setObjectName("label_2")
        MainWindow.setCentralWidget(self.centralwidget)

        self.retranslateUi(MainWindow)
        QtCore.QMetaObject.connectSlotsByName(MainWindow)

    def retranslateUi(self, MainWindow):
        _translate = QtCore.QCoreApplication.translate
        MainWindow.setWindowTitle(_translate("MainWindow", "MainWindow"))
        self.label.setText(_translate("MainWindow", "Management"))
        self.pushButton_back.setText(_translate("MainWindow", " Back"))
        self.groupBox.setTitle(_translate("MainWindow", "Group Management"))
        self.label_number_of_group.setText(_translate("MainWindow", "In database, there are 0 groups:"))
        self.pushButton_manage_group.setText(_translate("MainWindow", " Manage Group"))
        self.groupBox_2.setTitle(_translate("MainWindow", "Database Management"))
        self.pushButton_manage_person.setText(_translate("MainWindow", " Manage Database"))
        self.label_2.setText(_translate("MainWindow", "Group:"))


if __name__ == "__main__":
    import sys
    app = QtWidgets.QApplication(sys.argv)
    MainWindow = QtWidgets.QMainWindow()
    ui = Ui_MainWindow()
    ui.setupUi(MainWindow)
    MainWindow.show()
    sys.exit(app.exec_())
