# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'View.ui'
#
# Created by: PyQt5 UI code generator 5.15.9
#
# WARNING: Any manual changes made to this file will be lost when pyuic5 is
# run again.  Do not edit this file unless you know what you are doing.


from PyQt5 import QtCore, QtGui, QtWidgets


class Ui_MainWindow(object):
    def setupUi(self, MainWindow):
        MainWindow.setObjectName("MainWindow")
        MainWindow.resize(660, 600)
        MainWindow.setMinimumSize(QtCore.QSize(0, 0))
        MainWindow.setMaximumSize(QtCore.QSize(680, 620))
        MainWindow.setSizeIncrement(QtCore.QSize(680, 620))
        self.centralwidget = QtWidgets.QWidget(MainWindow)
        self.centralwidget.setObjectName("centralwidget")
        self.label_camera = QtWidgets.QLabel(self.centralwidget)
        self.label_camera.setGeometry(QtCore.QRect(10, 60, 640, 480))
        font = QtGui.QFont()
        font.setPointSize(12)
        self.label_camera.setFont(font)
        self.label_camera.setFrameShape(QtWidgets.QFrame.Box)
        self.label_camera.setAlignment(QtCore.Qt.AlignCenter)
        self.label_camera.setObjectName("label_camera")
        self.pushButton_take_photo = QtWidgets.QPushButton(self.centralwidget)
        self.pushButton_take_photo.setGeometry(QtCore.QRect(230, 550, 200, 40))
        font = QtGui.QFont()
        font.setPointSize(12)
        self.pushButton_take_photo.setFont(font)
        self.pushButton_take_photo.setObjectName("pushButton_take_photo")
        self.comboBox_camera = QtWidgets.QComboBox(self.centralwidget)
        self.comboBox_camera.setGeometry(QtCore.QRect(449, 10, 200, 40))
        font = QtGui.QFont()
        font.setPointSize(12)
        self.comboBox_camera.setFont(font)
        self.comboBox_camera.setObjectName("comboBox_camera")
        self.pushButton_back = QtWidgets.QPushButton(self.centralwidget)
        self.pushButton_back.setGeometry(QtCore.QRect(10, 10, 120, 40))
        font = QtGui.QFont()
        font.setPointSize(12)
        self.pushButton_back.setFont(font)
        self.pushButton_back.setObjectName("pushButton_back")
        MainWindow.setCentralWidget(self.centralwidget)

        self.retranslateUi(MainWindow)
        QtCore.QMetaObject.connectSlotsByName(MainWindow)

    def retranslateUi(self, MainWindow):
        _translate = QtCore.QCoreApplication.translate
        MainWindow.setWindowTitle(_translate("MainWindow", "MainWindow"))
        self.label_camera.setText(_translate("MainWindow", "TextLabel"))
        self.pushButton_take_photo.setText(_translate("MainWindow", " Take Photo"))
        self.pushButton_back.setText(_translate("MainWindow", " Back"))


if __name__ == "__main__":
    import sys
    app = QtWidgets.QApplication(sys.argv)
    MainWindow = QtWidgets.QMainWindow()
    ui = Ui_MainWindow()
    ui.setupUi(MainWindow)
    MainWindow.show()
    sys.exit(app.exec_())
