# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'View.ui'
#
# Created by: PyQt5 UI code generator 5.15.11
#
# WARNING: Any manual changes made to this file will be lost when pyuic5 is
# run again.  Do not edit this file unless you know what you are doing.


from PyQt5 import QtCore, QtGui, QtWidgets


class Ui_MainWindow(object):
    def setupUi(self, MainWindow):
        MainWindow.setObjectName("MainWindow")
        MainWindow.resize(800, 600)
        self.centralwidget = QtWidgets.QWidget(MainWindow)
        self.centralwidget.setObjectName("centralwidget")
        self.label_camera = QtWidgets.QLabel(self.centralwidget)
        self.label_camera.setGeometry(QtCore.QRect(80, 30, 640, 480))
        font = QtGui.QFont()
        font.setPointSize(12)
        self.label_camera.setFont(font)
        self.label_camera.setFrameShape(QtWidgets.QFrame.Box)
        self.label_camera.setAlignment(QtCore.Qt.AlignCenter)
        self.label_camera.setObjectName("label_camera")
        self.pushButton_take_photo = QtWidgets.QPushButton(self.centralwidget)
        self.pushButton_take_photo.setGeometry(QtCore.QRect(300, 530, 200, 40))
        font = QtGui.QFont()
        font.setPointSize(12)
        self.pushButton_take_photo.setFont(font)
        self.pushButton_take_photo.setObjectName("pushButton_take_photo")
        MainWindow.setCentralWidget(self.centralwidget)

        self.retranslateUi(MainWindow)
        QtCore.QMetaObject.connectSlotsByName(MainWindow)

    def retranslateUi(self, MainWindow):
        _translate = QtCore.QCoreApplication.translate
        MainWindow.setWindowTitle(_translate("MainWindow", "MainWindow"))
        self.label_camera.setText(_translate("MainWindow", "TextLabel"))
        self.pushButton_take_photo.setText(_translate("MainWindow", "Take Photo"))


if __name__ == "__main__":
    import sys
    app = QtWidgets.QApplication(sys.argv)
    MainWindow = QtWidgets.QMainWindow()
    ui = Ui_MainWindow()
    ui.setupUi(MainWindow)
    MainWindow.show()
    sys.exit(app.exec_())
